# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8b61ada386d4a8252cdbfad4e7505d06f02471733be5396fe8284f797e7f7ad5135ce4ffcded3667af29cfcfa515dbdd19b6864274536a6095d8454aaad9209

test:
  secret_key_base: 713878d8470740390003836e2cfd53a2bd025d5d8cb20e3d7ccb2c69cc8e2127c60dc2b4a4975034081ca977deb9238cba6fc96317ce92b178c07bcf2051daec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
